---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ashing.
--- DateTime: 2022/12/6 10:56
---

local function max(num1, num2)
    if num1 > num2 then
        result = num1; -- result 全局变量
    else
        result = num2; -- result 全局变量
    end

    return result
end

print(max(1,2 ))

local  myprint = function (param)
    print("print - ##", param, "##")
end

myprint("hello world")

-- 多返回值

local start_index, end_index = string.find("www.runoob.com", "runoob")
print(start_index, end_index)

function maximum (a)
    local mi = 1             -- 最大值索引
    local m = a[mi]          -- 最大值
    for i,val in ipairs(a) do
        if val > m then
            mi = i
            m = val
        end
    end
    return m, mi
end

print(maximum({8,10,23,12,5}))

-- 可变参数
local function add(...) -- ... 三点表示可变参数列表
    local s = 0
    print(select("#",...)) -- select 获取输入个数
    local arg = {...} -- 需要使用 {} 作为构造式
    for i, v in ipairs(arg) do   --> {...} 表示一个由所有变长参数构成的数组
        s = s + v
    end
    return s
end

print(add(3,4,5,6,7))  --->25

-- 固定参数必须放在变长参数之前
function fwrite(fmt, ...)  ---> 固定的参数fmt
return io.write(string.format(fmt, ...))
end

fwrite("hello\n")       --->fmt = "runoob", 没有变长参数。
fwrite("%d%d\n", 1, 2)   --->fmt = "%d%d", 变长参数为 1 和 2

--
local function f(...)
    -- select 会返回所有元素，如果只用一个参数去接，则只会拿到第一个
    -- https://blog.csdn.net/takashi77/article/details/116302058
    local a,b = select(3,...)  -->从第三个位置开始，变量 a 对应右边变量列表的第一个参数
    print (a, b)
    print (select(3,...)) -->打印所有列表参数
end

f(0,1,2,3,4,5)