---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ashing.
--- DateTime: 2022/12/11 00:40
---

mytable = {"apple", "orange", "banana"}

print(collectgarbage("count"))

mytable = nil

print(collectgarbage("count"))

print(collectgarbage("collect"))

print(collectgarbage("count"))

--/usr/local/bin/luajit-2.1.0-beta1 ~/Documents/lua-in-action/gc.lua
--31.28125
--31.28125
--0
--30.240234375