---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ashing.
--- DateTime: 2022/12/5 17:14
---

x = 10
local i = 1

while i < x do
    local x = i * 2
    print(x) -- 2,4,6..
    i = i + 1
end

print("====")
if i < 20 then
    local x -- 声明局部变量
    x = 20
    print(x + 2) -- 22
else
    print(x) -- 全局变量
end

print(x) -- 全局变量 10


a = 19
do
    local a =a
    a= 20
    print("a inside is",a)
end

print("a is",a)