---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ashing.
--- DateTime: 2022/12/9 14:40
---

mytable = { key1 = "value1" }
setmetatable(mytable, {
    __index = function(tt, key)
        for k, v in pairs(tt) do
            print("t is", k, v)
        end
        if key == "key2" then
            return "metatablevalue"
        else
            return nil
        end
    end
})

print(mytable.key1, mytable.key2, mytable.key3)


t1 = { key1 = "value1" }
setmetatable(t1, {
    __index = {
        key3 = "3value",
    }
})
print("t1 print start")
for k, v in pairs(t1) do
    print(k, v)
end
print("t1 print end")

print(t1.key1, t1.key2, t1.key3)

--- new index


mymetatable = {}
mytable = setmetatable({key1 = "value1"}, { __newindex = mymetatable })

print(mytable.key1)

mytable.newkey = "新值2"
print(mytable.newkey,mymetatable.newkey)

print("mymetatable print start")
for i, v in pairs(mymetatable) do
    print(i, v)
end
print("mymetatable print end")

mytable.key1 = "新值1"
print(mytable.key1,mymetatable.key1)

-- 当你给表的一个缺少的索引赋值，解释器就会查找__newindex 元方法：如果存在则调用这个函数而不进行赋值操作。

mytable = setmetatable({ 10, 20, 30 }, {
    __tostring = function(mytable)
        sum = 0
        for k, v in pairs(mytable) do
            sum = sum + v
        end
        return "表所有元素的和为 " .. sum
    end
})
print(mytable)