---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ashing.
--- DateTime: 2022/12/4 11:56
---

-- lua 交互模式中使用 dofile 进行加载
-- $ luajit
-- LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
-- JIT: OFF
-- > dofile("norm.lua")

function norm(x, y)
    return (x ^ 2 + y ^ 2) ^ 0.5
end

-- > n = norm(3.14,1.0)
-- > print(n)
-- 3.2953907203851

function twice(x)
    return 2 * x
end

-- > b = twice(4)
-- > print(b)
-- 8

function modify(y)
    return y.."world"
end


-- > c = modify("hello")
-- stdin:1: attempt to call global 'modify' (a nil value)
-- stack traceback:
-- stdin:1: in main chunk
-- [C]: at 0x0102f35954
-- > dofile("norm.lua") // 重新加载 dofile
-- > c = modify("hello")
-- > print(c)
-- helloworld