---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ashing.
--- DateTime: 2022/12/11 00:44
---

Account = {balance = 0}
function Account.withdraw (v)
    Account.balance = Account.balance - v
end

Account.withdraw(1)
print(Account.balance)