---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ashing.
--- DateTime: 2022/12/10 23:53
---

local function hello(num)
    print("num is", num)
    error("cause err")
end

if pcall(hello, 11) then
    print("ok")
else
    print("error")
end

xpcall(function(i)
    print(i)
    error('error..')
end, function(err)
    print("err is", err)
    print(debug.traceback())
end, 33)

function myfunction ()
    n = n / nil
end

function myerrorhandler(err)
    print("ERROR:", err)
end

status = xpcall(myfunction, myerrorhandler)
print(status)