---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ashing.
--- DateTime: 2022/12/5 00:21
---

a = "one string"
print("a is "..a)
b = string.gsub(a, "one", "another")
print("b is "..b)
print("a is "..a)

c = "I'm a student" -- 单引号
print("one line\nnext line\n\"in quotes\"")

print("\065") -- A

page = [[
<html>
    <body>
        <p> hello world </p>
    </body>
</html>
]]

print(page)

print("11"+1) -- 12 动态弱类型?

print(#a) -- # 表示获取长度 类似其他语言的 len
