---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ashing.
--- DateTime: 2022/12/4 17:32
---

print(type("hello"))
print(type(3.5))
a = print
print(type(a))
print(type(b)) -- 没有提前定义 所以是 nil
b = 10
print(type(b))
b = print
print(type(b))
print(type(true))

-- string
-- number
-- function
-- nil
-- number
-- function
-- boolean